spring:
  application:
    name: user-profile-service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

  endpoint:
    info:
      env:
        enabled: true
info:
  app:
    name: user-profile-service
